coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true
comment:
  layout: "reach, diff, files"
  behavior: default
